gallery/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import homePage, aboutPage, servicesPage, portfolioPage, pricingPage, supportPage

app_name = 'gallery'

urlpatterns = [
    path('', homePage.as_view(), name='home'),
    path('about/', aboutPage.as_view(), name="about"),
    path('services/', servicesPage.as_view(), name="services"),
    path('portfolio/', portfolioPage.as_view(), name="portfolio"),
    path('pricing/', pricingPage.as_view(), name="pricing"),
    path('contact-us/', supportPage.as_view(), name="support"),
]

photoshoop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('gallery.urls', 'gallery'), namespace="gallery"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gallery/models.py
from django.db import models

# Create your models here.

gallery/models/categoryModels.py
from django.db import models
import uuid


class Category(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    name = models.CharField(max_length=50, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

gallery/models/photoModels.py
from django.db import models
import uuid
from .categoryModels import Category
from django.core.exceptions import ValidationError

def validate_image_size(value):
    max_size = 5 * 1024 * 1024
    if value.size > max_size:
        raise ValidationError("Image file too large (max 5 MB).")


class Photo(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    picture = models.ImageField(upload_to='gallery/', max_length=1000, validators=[validate_image_size])
    date = models.DateTimeField(auto_now_add=True)

gallery/models/pricingModel.py
from django.db import models
import uuid

class Pricing(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    plansOptions = models.TextChoices("Plans", "Basic Standard Managed")
    plans  = models.CharField(max_length=20, choices=plansOptions, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    

gallery/models/reviewModels.py
from django.db import models
import uuid
from django.core.exceptions import ValidationError

def validate_review_picture_size(value):
    max_size = 5 * 1024 * 1024
    if value.size > max_size:
        raise ValidationError("Image file too large (max 5 MB).")

class Review(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    name =  models.CharField(max_length=100, null=True, blank=True)
    title = models.CharField(max_length=100, null=True, blank=True)
    info = models.TextField(max_length=300, null=True, blank=True)
    profile_picture = models.ImageField(upload_to='customer_profiePic/', validators=[validate_review_picture_size],null=True, blank=True) 
    date = models.DateTimeField(auto_now_add=True)

gallery/models/serviceModels.py
from django.db import models
import uuid

class Service(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    title = models.CharField(max_length=100, null=True, blank=True)
    info = models.TextField(max_length=300, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

gallery/models/subscriberModels.py
from django.db import models
import uuid 

class Subscriber(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add=True)

gallery/models/visitorsModels.py
from django.db import models
import uuid 

class Visitor(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)
    ip = models.JSONField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

gallery/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, View
from .models import Photo,Service, Review, Pricing

class homePage(ListView):
    template_name = 'index.html'
    model = Photo
    context_object_name = 'gallery'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        context['reviews'] = Review.objects.all()
        context['plans'] = Pricing.objects.all()
        return context

class aboutPage(View):
    template_name = 'about-us.html'

    def get(self, request, *args, **kwargs):
        services = Service.objects.all()
        reviews = Review.objects.all()
        context = {'services': services, 'reviews': reviews}
        return render(request, self.template_name, context)

class servicesPage(View):
    template_name = 'services.html'

    def get(self, request, *args, **kwargs):
        services = Service.objects.all()
        reviews = Review.objects.all()
        context = {'services': services, 'reviews': reviews}
        return render(request, self.template_name, context)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        context['reviews'] = Review.objects.all()
        context['plans'] = Pricing.objects.all()
        return context

class portfolioPage(ListView):
    template_name = 'portfolio.html'
    model = Photo
    context_object_name = 'gallery'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = Review.objects.all()
        return context

class pricingPage(View):
    template_name = 'pricing.html'

    def get(self, request, *args, **kwargs):
        price_plans = Pricing.objects.all()
        context = {'plans': price_plans}
        context['reviews'] = Review.objects.all()
        return render(request, self.template_name, context)

class supportPage(View):
    template_name = "contact-us.html"

    def get(self, request, *args, **kwargs):
        price_plans = Pricing.objects.all()
        context = {'plans': price_plans}
        context['reviews'] = Review.objects.all()
        return render(request, self.template_name, context)

templates/about-us.html
{% extends 'pageheader/header.html' %}
{% load static %}

    
        
    {% block meta_seo %}
        
        {% with  author="PhotoShoot" keywords="about, photo, know about us" meta_descripiton="About us page - PhotoShoot" meta_title="About Us" %}
            {{block.super}}
        {% endwith %}
            
    {% endblock meta_seo %}
    

    {% block content %}

    
    {% block nav %}{{block.super}}{% endblock nav %}
        

	
	
    {% block page_info %}
		{% with page_name="About" %}
            {{block.super}} 
    {% endwith %}
    {% endblock %}
        
	
    <div id="about" class="section wb">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-6">
                    <div class="message-box">                        
                        <h2> Welcome To PhotoShoot</h2>
                        <p> Integer rutrum ligula eu dignissim laoreet. Pellentesque venenatis nibh sed tellus faucibus bibendum. Sed fermentum est vitae rhoncus molestie. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed vitae rutrum neque. Ut id erat sit amet libero bibendum aliquam. Donec ac egestas libero, eu bibendum risus. Phasellus et congue justo. Integer rutrum ligula eu dignissim laoreet. Pellentesque venenatis nibh sed tellus faucibus bibendum. Sed fermentum est vitae rhoncus molestie. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
						<p>Sed vitae rutrum neque. Ut id erat sit amet libero bibendum aliquam. Donec ac egestas libero, eu bibendum risus. Phasellus et congue justo.</p>
						
                        <a href="#" class="hover-effect-new"><span>Lorem Ipsum</span></a>
                    </div><!-- end messagebox -->
                </div><!-- end col -->

                <div class="col-md-6">
                    <div class="right-box-pro wow fadeIn">
                        <img src="{% static 'uploads/about_02.jpg' %}" alt="" class="img-fluid img-rounded">
                    </div><!-- end media -->
                </div><!-- end col -->
            </div><!-- end row -->
			
			<div class="row">
                <div class="col-md-6">
                    <div class="right-box-pro wow fadeIn">
                        <img src="{% static 'uploads/about_03.jpg' %}" alt="" class="img-fluid img-rounded">
                    </div><!-- end media -->
                </div><!-- end col -->
				
				<div class="col-md-6">
                    <div class="message-box">                        
                        <h2> What we do</h2>
                        <p> Integer rutrum ligula eu dignissim laoreet. Pellentesque venenatis nibh sed tellus faucibus bibendum. Sed fermentum est vitae rhoncus molestie. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed vitae rutrum neque. Ut id erat sit amet libero bibendum aliquam. Donec ac egestas libero, eu bibendum risus. Phasellus et congue justo. Integer rutrum ligula eu dignissim laoreet. Pellentesque venenatis nibh sed tellus faucibus bibendum. Sed fermentum est vitae rhoncus molestie. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
						<p>Sed vitae rutrum neque. Ut id erat sit amet libero bibendum aliquam. Donec ac egestas libero, eu bibendum risus. Phasellus et congue justo.</p>
						
                        <a href="#" class="hover-effect-new"><span>Lorem Ipsum</span></a>
                    </div><!-- end messagebox -->
                </div><!-- end col -->
				
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->
	
    <div id="services" class="section lb">
		<div class="container">
			<div class="section-title text-center">
				<h3>Services</h3>
				<p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.
				</p>
			</div><!-- end title -->

			<div class="row">
				
				{% for service in services %}
				<div class="col-md-4">
					<div class="effect-new">
						<div class="services-inner-box">
							<div class="ser-icon">
								<i class="flaticon-{% cycle 'wedding-photo' 'image' 'event' %}"></i>
							</div>
							<h2>{{service.title|title}}</h2>
							<p>{{service.info}}</p>
						</div>
					</div>
				</div>
				{% endfor %}
				
				
			</div><!-- end row -->
		</div><!-- end container -->
	</div><!-- end section -->

	
	{% block review %}
		{{block.super}}
	{% endblock review %}
		
	
{% endblock %}

templates/contact-us.html
{% extends 'pageheader/header.html' %}
{% load static %}
	
	   {% block meta_seo %}
        
        {% with  author="PhotoShoot" keywords="contact, photo, know contact us" meta_descripiton="Contact us page - PhotoShoot" meta_title="Contact Us" %}
            {{block.super}}
        {% endwith %}
            
    {% endblock meta_seo %}


	{% block content %}
		

	{% block nav %}
		{{block.super}}
	{% endblock nav %}

		
	
		{% block page_info %}
	
		{% with page_name="Contact Us" %}
			{{block.super}}
		{% endwith %}
		
		{% endblock page_info %}
	
    <div id="contact" class="section lb">
        <div class="container">
            <div class="section-title text-center">
                <h3>Contact Us</h3>
                <p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p>
            </div><!-- end title -->

            <div class="row">
                <div class="col-md-12">
                    <div class="contact_form">
                        <div id="message"></div>
                        <form id="contactForm" name="sentMessage" novalidate="novalidate">
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<input class="form-control" id="name" type="text" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name.">
										<p class="help-block text-danger"></p>
									</div>
									<div class="form-group">
										<input class="form-control" id="email" type="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email address.">
										<p class="help-block text-danger"></p>
									</div>
									<div class="form-group">
										<input class="form-control" id="phone" type="tel" placeholder="Your Phone" required="required" data-validation-required-message="Please enter your phone number.">
										<p class="help-block text-danger"></p>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<textarea class="form-control" id="message" placeholder="Your Message" required="required" data-validation-required-message="Please enter a message."></textarea>
										<p class="help-block text-danger"></p>
									</div>
								</div>
								<div class="clearfix"></div>
								<div class="col-lg-12 text-left">
									<div id="success"></div>
									<button id="sendMessageButton" class="hover-effect-new" data-text="Send Message" type="submit"><span>Send Message</span></button>
								</div>
							</div>
						</form>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->
	
	<div data-key="AIzaSyAiKl_QPZ8L92aLRfpH23F5jzEuIETEhWw" data-zoom="14" role="map" class="gmaps">
        <div data-id="1" data-lat="-33.4727092" data-lng="-70.7699143" class="marker">
          <div class="map-card">
            <h1>PhotoShoot</h1>
            <p>Address: demo street, #445, Stgo.</p>
            <p>Phone: +56753223344</p>
            <p>e-Mail: demo@email.com</p>
          </div>
        </div>

    </div>
	
		
		{% block review %}
			{{block.super}}
		{% endblock review %}
			
{% endblock %}

templates/pageheader/footer.html
{% load static %}
<footer class="main-footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-6 col-sm-12">
				<div class="mb-3 img-logo">
					<a href="#">
						<img src="{% static 'images/logo2.png' %}" alt="">
					</a>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
						labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
						laboris nisi ut aliquip ex ea commodo consequat.</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-12">
				<h4 class="mb-4 ph-fonts-style foot-title">
					RECENT NEWS
				</h4>
				<p class="ph-links-column">
					<a href="{% url 'gallery:about' %}" class="text-black">About us</a>
					<a href="{% url 'gallery:services' %}" class="text-black">Services</a>
					<a href="{% url 'gallery:portfolio' %}" class="text-black">Selected Work</a>
					<a href="{% url 'gallery:home' %}" class="text-black">Get In Touch</a>
					<a href="{% url 'gallery:home' %}" class="text-black">Careers</a>
				</p>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-12">
				<h4 class="mb-4 ph-fonts-style foot-title">
					CATEGORIES
				</h4>
				<p class="ph-links-column">
					<a href="#" class="text-black">Business</a>
					<a href="#" class="text-black">Design</a>
					<a href="#" class="text-black">Real life</a>
					<a href="#" class="text-black">Science</a>
					<a href="#" class="text-black">Tech</a>
				</p>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-12">
				<h4 class="mb-4 ph-fonts-style foot-title">
					SUBSCRIBE
				</h4>
				<p class="ph-fonts-style_p">
					Get monthly updates and free resources.
				</p>
				<div class="media-container-column" data-form-type="formoid">
					<div data-form-alert="" class="align-center" hidden="">
						Thanks for filling out the form!
					</div>

					<form class="form-inline" action="#" method="post">
						<input value="" data-form-email="true" type="hidden">
						<div class="form-group">
							<input class="form-control input-sm input-inverse my-2" name="email" required=""
								data-form-field="Email" placeholder="Email" id="email" type="email">
						</div>
						<div class="input-group-btn">
							<button href="" class="btn hover-effect-new btn-primary" type="submit"
								role="button"><span> Subscribe </span></button>
						</div>
					</form>
				</div>

			</div>
		</div>
	</div>
</footer>

<div class="copyrights">
	<div class="container">
		<div class="footer-distributed">
			<div class="footer-left">
				<p class="footer-company-name">AQO projects &copy; 2025 
				</p>
			</div>
		</div>
	</div><!-- end container -->
</div><!-- end copyrights -->
    <!-- ALL JS FILES -->
    <script src="{% static 'js/all.js' %}"></script>
	<!-- Camera Slider -->
	<script src="{% static 'js/jquery.mobile.customized.min.js' %}"></script>
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script> 
	<script src="{% static 'js/parallaxie.js' %}"></script>
	<script src="{% static 'js/jquery.appear.min.js' %}"></script>
	<script src="{% static 'js/skill.bars.jquery.js' %}"></script>
	<script src="{% static 'js/responsiveslides.min.js' %}"></script>
	<!-- Contact form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>
    <!-- ALL PLUGINS -->
	<script src="{% static 'js/jquery.fatNav.min.js' %}"></script>
	<script src="{% static 'js/menu-overlay.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
	<script src="{% static 'js/zepto.min.js' %}"></script>
	<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
	<script src="{% static 'js/slider.js' %}"></script>

templates/pageheader/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Mobile Metas -->
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

{% block meta_seo %}
<!-- Site Metas -->
<title>{{meta_title|default:'PhotoShoot - Photography &amp; Portfolio'}}</title>

<!-- HTML SEO META  -->
<meta name="keywords" content="{{keywords|default:'pictures, photos, gallery, studio, 4k images, portfolio, camera'}}">
<meta name="description" content="{{meta_descripiton|default:'PhotoShoot - Photography &amp; Portfolio'}}">
<meta name="author" content="{{author|default:'PhotoShoot'}}">



	
	<meta property="og:title" content="{{meta_title|default:'PhotoShoot - Photography &amp; Portfolio'}}">
	<meta property="og:description" content="{{meta_descripiton|default:'PhotoShoot - Photography &amp; Portfolio'}}">
	<meta property="og:image" content="{% static 'images/favicon.ico' %}">
	<meta property="og:type" content="{{request.get_host}}">
	<meta property="og:url" content="{{request.path}}">
	<meta property="twitter:card" content="{% static 'images/apple-touch-icon.png' %}">
	<meta property="twitter:site" content="@phootshoot">
	<meta property="twitter:title" content="{{meta_title|default:'PhotoShoot - Photography &amp; Portfolio'}} - PhotoShoot">
	<meta property="twitter:description" content="{{meta_descripiton|default:'PhotoShoot - Photography &amp; Portfolio'}}">
	<meta property="twitter:image" content="{% static 'images/apple-touch-icon.png' %}">
{% endblock  %}
	

<!-- Site Icons -->
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
<link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!-- Site CSS -->
<link rel="stylesheet" href="{% static 'style.css' %}">
<!-- Responsive CSS -->
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<script src="{% static 'js/modernizr.js' %}"></script> <!-- Modernizr -->

<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="politics_version">
    
	<!-- LOADER -->
	<div id="preloader">
		<div class="loader-rd"></div>
		<div class="loader-rd"></div>
		<div class="loader-rd"></div>
		<div class="loader-rd"></div>
	</div><!-- end loader -->
	<!-- END LOADER -->
    {% block content %}
    
    {% block nav %}
    {% include 'pageheader/navmenu.html' %}
    {% endblock nav %}

    
    {% block page_info %}
    <div class="banner-area banner-bg-1">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="banner">
						<h2>
                            
                            {{ page_name|default:"Home" }}
                                
                            </h2>
						<ul class="page-title-link">
							<li><a href="{% url 'gallery:home' %}">Home</a></li>
							<li><a href="#">{{ page_name|default:"Home" }}</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
    {% endblock page_info %}
    
    
    {% block review %}
    {% include 'pageheader/review.html' %}
    {% endblock review %}
        

    {% endblock %}
	<a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-paper-plane-o"
        aria-hidden="true"></i></a>

    {% include 'pageheader/footer.html' %}
    


</body>


</html>

templates/pageheader/navmenu.html
{% load static %}
<header class="header">
	<div class="burger">
		<div class="burger__patty"></div>
		<div class="burger__patty"></div>
		<div class="burger__patty"></div>
	</div>

		<nav class="menu">
		<div class="menu__brand">
			<a href="{% url 'gallery:home' %}"><div class="logo"><img class="img-fluid" src="{% static 'images/logo.png' %}" alt="" /></div></a>
		</div>
		
		<ul class="menu__list">
			<li class="menu__item"><a href="{% url 'gallery:home' %}" class="menu__link">Home</a></li>
			<li class="menu__item"><a href="{% url 'gallery:about' %}" class="menu__link">About Us</a></li>
			<li class="menu__item"><a href="{% url 'gallery:services' %}" class="menu__link">Services</a></li>
			<li class="menu__item"><a href="{% url 'gallery:portfolio' %}" class="menu__link">Portfolio</a></li>
			<li class="menu__item"><a href="{% url 'gallery:pricing' %}" class="menu__link">Pricing</a></li>
			<li class="menu__item"><a href="{% url 'gallery:support' %}" class="menu__link">Contact Us</a></li>
		</ul>
	</nav>
</header>


    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container-fluid">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'gallery:home' %}">
			<img class="img-fluid" src="{% static 'images/logo.png' %}" alt="" />
		</a>
      </div>
    </nav>
	

templates/pageheader/review.html
{% load static %}
<div id="reviews" class="section wb parallaxie" style="background: url({% static 'uploads/reviews-bg.jpg' %}) ">
  <div class="container">
    <div class="section-title text-center">
      <h3>Reviews</h3>
      <p>We thanks for all our awesome testimonials! There are hundreds of our happy customers! </p>
    </div><!-- end title -->

    <div class="row">
      <div class="col-md-12 col-sm-12">
        <div class="testi-carousel owl-carousel owl-theme">

          
          {% for review in reviews %}
          <div class="testimonial clearfix">
            <figure class="testimonial_img">
              <img src="{{review.profile_picture.url}}" alt="" class="img-fluid">
            </figure>
            <div class="desc">
              <h3><i class="fa fa-quote-left"></i>{{review.title|title}}</h3>
              <p>{{review.info}}</p>
            </div>
            <div class="testi-meta">
              <h4>{{review.name}} </h4>
            </div>
            <!-- end testi-meta -->
          </div>
          <!-- end testimonial -->
          {% endfor %}

          
        </div><!-- end carousel -->
      </div><!-- end col -->
    </div><!-- end row -->
  </div><!-- end container -->
</div><!-- end section -->

templates/portfolio.html
{% extends 'pageheader/header.html' %}
{% load static %}

	   {% block meta_seo %}
        
        {% with  author="PhotoShoot" keywords="portfolio, photo, know pictures photos" meta_descripiton="Portfolio page - PhotoShoot" meta_title="Portfolio" %}
            {{block.super}}
        {% endwith %}
            
    {% endblock meta_seo %}


	{% block content %}
		


	{% block nav %}
		{{block.super}}
	{% endblock nav %}
	

	
	{% block page_info %}
	
	{% with page_name="Portfolio" %}
		{{block.super}}
	{% endwith %}
	
	{% endblock page_info %}
		
	
    <div id="gallery" class="section lb">
		<div class="container">
			<div class="section-title text-center">
				<h3>Gallery</h3>
				<p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.
				</p>
			</div><!-- end title -->

			<div class="gallery-menu text-center row">
				<div class="col-md-12">
					<div class="button-group filter-button-group">
						<button class="active" data-filter="*">All</button>
						<button data-filter=".photo_a">Wedding</button>
						<button data-filter=".photo_b">Models</button>
						<button data-filter=".photo_c">Fashion</button>
					</div>
				</div>
			</div>

			<div class="gallery-list row">
				
				{% for photo in gallery %}
				<div class="col-md-4 col-sm-6 gallery-grid {% cycle 'photo_a' 'photo_b' 'photo_c' %}">
					<div class="gallery-single fix">
						<img src="{{photo.picture.url}}" class="img-fluid" alt="Image">
						<div class="box-content">
							<div class="inner-content">
								<h3 class="title">{{photo.category|title}}</h3>
								<span class="post">Latest Photo</span>
							</div>
							<ul class="icon">
								<li><a href="{{photo.picture.url}}" data-rel="prettyPhoto[gal]"><i
											class="fa fa-search"></i></a></li>
								<li><a href="#"><i class="fa fa-link"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
				{% endfor %}

			</div>
		</div>
	</div>
	
	
	{% block review %}
		{{block.super}}
	{% endblock review %}
		
	{% endblock content %}

	